apiVersion: v1
kind: Pod
metadata:
  name: s3-cache-pod-a
spec:
  nodeSelector:
    node.kubernetes.io/instance-type: ml.g5.8xlarge
  tolerations:
    - key: nvidia.com/gpu
      operator: Equal
      value: "true"
      effect: NoSchedule
  containers:
    - name: app
      image: amazonlinux:2023
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: s3-vol
          mountPath: /data/s3
  volumes:
    - name: s3-vol
      persistentVolumeClaim:
        claimName: s3-pvc-cached
---
apiVersion: v1
kind: Pod
metadata:
  name: s3-cache-pod-b
spec:
  nodeSelector:
    node.kubernetes.io/instance-type: ml.g5.8xlarge
  tolerations:
    - key: nvidia.com/gpu
      operator: Equal
      value: "true"
      effect: NoSchedule
  containers:
    - name: app
      image: amazonlinux:2023
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: s3-vol
          mountPath: /data/s3
  volumes:
    - name: s3-vol
      persistentVolumeClaim:
        claimName: s3-pvc-cached
