apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv-cached
spec:
  capacity:
    storage: 1200Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - allow-delete
    - metadata-ttl indefinite
    - region ap-southeast-1
    - read-part-size 67108864
    - maximum-throughput-gbps 25
  csi:
    driver: s3.csi.aws.com
    volumeHandle: s3-csi-testbucketjason99-cached
    volumeAttributes:
      bucketName: testbucketjason99
      cache: ephemeral
      cacheEphemeralStorageClassName: nvme-local
      cacheEphemeralStorageResourceRequest: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-pvc-cached
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1200Gi
  volumeName: s3-pv-cached
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: s3-cache-test
spec:
  selector:
    matchLabels:
      app: s3-cache-test
  template:
    metadata:
      labels:
        app: s3-cache-test
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node.kubernetes.io/instance-type
                    operator: In
                    values:
                      - ml.g6e.xlarge
                      - ml.g5.8xlarge
      tolerations:
        - key: nvidia.com/gpu
          operator: Equal
          value: "true"
          effect: NoSchedule
      containers:
        - name: app
          image: amazonlinux:2023
          command: ["sleep", "infinity"]
          volumeMounts:
            - name: s3-vol
              mountPath: /data/s3
      volumes:
        - name: s3-vol
          persistentVolumeClaim:
            claimName: s3-pvc-cached
